### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by baptx** [KunYi/hardware_asix_usbnet#1]
I noticed that latest version of the USB 3.0 to Gigabit Ethernet adapter driver can be downloaded here:
https://www.asix.com.tw/download.php?sub=driverdetail&PItemID=131
https://www.asix.com.tw/products.php?op=pItemdetail&PItemID=131;71;112

Maybe you could update your repository with this version.
By the way, do you know where we can find the revision history of the latest version? Where did you find the revision history displayed on your repository?
I also noticed that there is an usbnet driver in the official Linux kernel repository (https://github.com/torvalds/linux/blob/master/drivers/net/usb/usbnet.c), do you know the difference with the usbnet driver from ASIX?

For information, I think there is a mistake with the name "axis" you used in your repository, I guess you meant "asix".

**Comment by KunYi** [comment]
Dear @baptx ,
     sorry, I missed you issues comment, 
     about the change history, need to contact FAE of ASIX,
     the version have been apply into latest asix driver,
     and independence upstream linux driver
     the driver for my project transfer performance turning on ARM platform
